export const languages = {
  English: "🇬🇧",
  German: "🇩🇪",
  Spanish: "🇪🇸",
  French: "🇫🇷",
  Italian: "🇮🇹",
  Polish: "🇵🇱",
  Russian: "🇷🇺",
  Portuguese: "🇵🇹",
  Japanese: "🇯🇵",
  Chinese: "🇨🇳",
  Turkish: "🇹🇷",
  Dutch: "🇳🇱",
  Romanian: "🇷🇴",
  Arabic: "🇸🇦",
};
